"""Render a frozen author-list snapshot as plain text, LaTeX (authblk),
or INSPIRE/arXiv authors.xml."""

from xml.sax.saxutils import escape as xml_escape

TEX_SPECIALS = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def tex_escape(s: str) -> str:
    return "".join(TEX_SPECIALS.get(c, c) for c in s)


def _inst_indices(author: dict, institutions: dict) -> list[int]:
    return sorted(
        institutions[str(i)]["index"]
        for i in author["institution_ids"]
        if str(i) in institutions
    )


def render_txt(snapshot: dict) -> str:
    institutions = snapshot["institutions"]
    lines = []
    for a in snapshot["authors"]:
        idx = _inst_indices(a, institutions)
        sup = ",".join(str(i) for i in idx)
        name = f"{a['given_name'][0]}. {a['family_name']}" if a["given_name"] else a["family_name"]
        lines.append(f"{name}^{{{sup}}}" if sup else name)
    body = ", ".join(lines)

    inst_lines = [
        f"{v['index']}. {v['name']}"
        for v in sorted(institutions.values(), key=lambda v: v["index"])
    ]
    return (
        f"US Muon Collider Collaboration author list "
        f"(cutoff {snapshot['cutoff_date']}, {len(snapshot['authors'])} authors)\n\n"
        + body
        + "\n\n"
        + "\n".join(inst_lines)
        + "\n"
    )


def render_tex(snapshot: dict) -> str:
    institutions = snapshot["institutions"]
    out = [
        "% US Muon Collider Collaboration author list",
        f"% cutoff date: {snapshot['cutoff_date']}",
        f"% {len(snapshot['authors'])} authors — generated by USMCC DB",
        "% Requires: \\usepackage{authblk}",
        "",
    ]
    for a in snapshot["authors"]:
        idx = _inst_indices(a, institutions)
        sup = ",".join(str(i) for i in idx)
        out.append(f"\\author[{sup}]{{{tex_escape(a['display_name'])}}}")
    out.append("")
    for v in sorted(institutions.values(), key=lambda v: v["index"]):
        address = v["latex_address"] or v["name"]
        out.append(f"\\affil[{v['index']}]{{{tex_escape(address)}}}")
    out.append("")
    return "\n".join(out)


def render_xml(snapshot: dict) -> str:
    """INSPIRE-style authors.xml (cal/foaf schema) accepted by arXiv."""
    institutions = snapshot["institutions"]
    out = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<collaborationauthorlist",
        '    xmlns:foaf="http://xmlns.com/foaf/0.1/"',
        '    xmlns:cal="http://inspirehep.net/info/HepNames/tools/authors_xml/">',
        "  <cal:creationDate>" + xml_escape(snapshot["cutoff_date"]) + "</cal:creationDate>",
        "  <cal:publicationReference>USMCC</cal:publicationReference>",
        "  <cal:collaborations>",
        '    <cal:collaboration id="c1">',
        "      <foaf:name>US Muon Collider Collaboration</foaf:name>",
        "    </cal:collaboration>",
        "  </cal:collaborations>",
        "  <cal:organizations>",
    ]
    for v in sorted(institutions.values(), key=lambda v: v["index"]):
        out += [
            f'    <foaf:Organization id="o{v["index"]}">',
            f"      <foaf:name>{xml_escape(v['name'])}</foaf:name>",
            "      <cal:orgStatus collaborationid=\"c1\">member</cal:orgStatus>",
            "    </foaf:Organization>",
        ]
    out.append("  </cal:organizations>")
    out.append("  <cal:authors>")
    for a in snapshot["authors"]:
        idx = _inst_indices(a, institutions)
        out += [
            "    <foaf:Person>",
            f"      <foaf:givenName>{xml_escape(a['given_name'])}</foaf:givenName>",
            f"      <foaf:familyName>{xml_escape(a['family_name'])}</foaf:familyName>",
            f"      <cal:authorNamePaper>{xml_escape(a['display_name'])}</cal:authorNamePaper>",
            "      <cal:authorAffiliations>",
        ]
        for i in idx:
            out.append(f'        <cal:authorAffiliation organizationid="o{i}" connection="" />')
        out.append("      </cal:authorAffiliations>")
        if a.get("orcid"):
            out.append(
                '      <cal:authorids><cal:authorid source="ORCID">'
                + xml_escape(a["orcid"])
                + "</cal:authorid></cal:authorids>"
            )
        out.append("    </foaf:Person>")
    out += ["  </cal:authors>", "</collaborationauthorlist>", ""]
    return "\n".join(out)


RENDERERS = {"txt": render_txt, "tex": render_tex, "xml": render_xml}
CONTENT_TYPES = {
    "txt": "text/plain; charset=utf-8",
    "tex": "application/x-tex; charset=utf-8",
    "xml": "application/xml; charset=utf-8",
}
